/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestion_de_agenda_reuniones.ventanas;

import com.mycompany.gestion_de_agenda_reuniones.Actividad;
import com.mycompany.gestion_de_agenda_reuniones.Agenda;
import com.mycompany.gestion_de_agenda_reuniones.ClaseUniversitaria;
import com.mycompany.gestion_de_agenda_reuniones.Evaluacion;
import com.mycompany.gestion_de_agenda_reuniones.Reunion;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tomas
 */
public class VentanaReporteActividades extends javax.swing.JFrame {

    /**
     * Creates new form VentanaReporteActividades
     */
    private Agenda actividades;
    public VentanaReporteActividades(Agenda actividades) {
        initComponents();
        this.actividades = actividades;
        cargarTablaActividades();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblActividades = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo de Actividad", "Hora Inicio", "Hora Final", "Título ", "Detalles"
            }
        ));
        jScrollPane2.setViewportView(tblActividades);
        if (tblActividades.getColumnModel().getColumnCount() > 0) {
            tblActividades.getColumnModel().getColumn(0).setPreferredWidth(120);
            tblActividades.getColumnModel().getColumn(0).setMaxWidth(120);
            tblActividades.getColumnModel().getColumn(1).setResizable(false);
            tblActividades.getColumnModel().getColumn(1).setPreferredWidth(70);
            tblActividades.getColumnModel().getColumn(2).setResizable(false);
            tblActividades.getColumnModel().getColumn(2).setPreferredWidth(70);
            tblActividades.getColumnModel().getColumn(3).setPreferredWidth(200);
            tblActividades.getColumnModel().getColumn(4).setPreferredWidth(300);
        }

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Reporte Actividades");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(405, 405, 405))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarTablaActividades(){
          List<Actividad> catalogoCompleto = actividades.obtenerTodoElCatalogo();
          DefaultTableModel modelo = (DefaultTableModel) tblActividades.getModel();
        
        
        // 4. Recorremos la lista y creamos las filas
        for (Actividad act : catalogoCompleto) {
            String tipoClase = act.getTipoClase();
            LocalTime horaInicio = act.getHoraInicio();
            LocalTime horaFin = act.getHoraFin();
            String titulo = act.getTitulo();
            String detalles = null;
            switch(tipoClase){
                case"REUNION":
                    Reunion auxReunion = (Reunion)act;
                    detalles = "Anfitrion: " + auxReunion.getAnfitrion();
                    modelo.addRow(new Object[]{ tipoClase.toUpperCase(),horaInicio , horaFin, titulo , detalles });
                    break;
                case"EVALUACION":
                    Evaluacion auxEvaluacion = (Evaluacion)act;
                    detalles ="Ponderación: " + auxEvaluacion.getPonderacion() + "% | Temas: " + auxEvaluacion.getTemario();
                    modelo.addRow(new Object[]{ tipoClase.toUpperCase(),horaInicio , horaFin, titulo , detalles });
                    break;
                case"CLASE":
                    ClaseUniversitaria auxClase =(ClaseUniversitaria)act;
                    detalles = "Prof: " + auxClase.getProfesor() + " | Sala: " + auxClase.getSala();
                    modelo.addRow(new Object[]{ tipoClase.toUpperCase(),horaInicio , horaFin, titulo , detalles });
                    break;
                    
            }

        }
    }


    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblActividades;
    // End of variables declaration//GEN-END:variables
}
