/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestion_de_agenda_reuniones.ventanas;

import com.mycompany.gestion_de_agenda_reuniones.Actividad;
import com.mycompany.gestion_de_agenda_reuniones.Agenda;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author tomas
 */
public class VentanaEliminarActividad extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEliminarActividad
     */
    private Agenda actividades;
    public VentanaEliminarActividad(Agenda actividades) {
        initComponents();
        this.actividades = actividades;
        cargarFechas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxFechas = new javax.swing.JComboBox<>();
        cbxActividades = new javax.swing.JComboBox<>();
        btnActualizarActividades = new javax.swing.JButton();
        btnEliminarActividad1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Elige una fecha de la agenda: ");

        jLabel2.setText("Elige una actividad : ");

        btnActualizarActividades.setText("Actualizar");
        btnActualizarActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActividadesActionPerformed(evt);
            }
        });

        btnEliminarActividad1.setText("Eliminar");
        btnEliminarActividad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActividad1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setText("Eliminar Actividad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxFechas, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizarActividades)
                        .addGap(16, 16, 16))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(btnEliminarActividad1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnActualizarActividades))
                .addGap(53, 53, 53)
                .addComponent(btnEliminarActividad1)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarFechas(){
         cbxFechas.removeAllItems();
         DateTimeFormatter formato = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
         List<LocalDate> fechas = actividades.getDiasHabilitados();
         for( LocalDate fecha : fechas ){
         cbxFechas.addItem(fecha.format(formato));

        }
    }
         
    
    private void cargarActividadesCbx(LocalDate fecha){
         List<Actividad> listActividades = actividades.getActividades(fecha);
         for(Actividad actividad : listActividades){
             String detalles = "[" + actividad.getId() + "] " + actividad.getTipoClase() + " | " + actividad.getTitulo();
             cbxActividades.addItem(detalles);
         }
    }
    
    private void btnActualizarActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActividadesActionPerformed
        // TODO add your handling code here:
        cbxActividades.removeAllItems();
        String fechaSelec = cbxFechas.getSelectedItem().toString();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");        
        LocalDate fechaFinal = LocalDate.parse(fechaSelec, formato);
        cargarActividadesCbx(fechaFinal);
        
    }//GEN-LAST:event_btnActualizarActividadesActionPerformed

    private void btnEliminarActividad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActividad1ActionPerformed
        // TODO add your handling code here:
        String seleccion = cbxActividades.getSelectedItem().toString();
        
        String fechaSelec = cbxFechas.getSelectedItem().toString();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");        
        LocalDate fechaFinal = LocalDate.parse(fechaSelec, formato);
        
        // Cortamos el texto: desde el carácter 1, hasta donde está el "]"
        String idParaEliminar = seleccion.substring(1, seleccion.indexOf("]")); 

        // Ahora vas a tu Agenda y buscas la actividad en esa fecha que tenga ese ID exacto para borrarla   
        actividades.eliminarActividadPorId(fechaFinal, idParaEliminar);
        JOptionPane.showMessageDialog(this, "¡Actividad , con ID: " + idParaEliminar + "eliminada con exito!");
        this.dispose();
        
    }//GEN-LAST:event_btnEliminarActividad1ActionPerformed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarActividades;
    private javax.swing.JButton btnEliminarActividad1;
    private javax.swing.JComboBox<String> cbxActividades;
    private javax.swing.JComboBox<String> cbxFechas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
