/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestion_de_agenda_reuniones.ventanas;
import com.mycompany.gestion_de_agenda_reuniones.Agenda;

/**
 *
 * @author benjja
 */
public class VentanaMenuMain extends javax.swing.JFrame {

    private Agenda actividades;
    public VentanaMenuMain(Agenda actividades) {
        initComponents();
        
        this.actividades = actividades;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        btnAgregarActividad = new javax.swing.JButton();
        btnEliminarDiaAgenda = new javax.swing.JButton();
        btnVerReporteDias = new javax.swing.JButton();
        btnHabilitarDiaAgenda = new javax.swing.JButton();
        btnVerReporteActividades = new javax.swing.JButton();
        btnEliminarActividadDia = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Myanmar Sangam MN", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agenda de actividades");

        btnAgregarActividad.setText("Agregar actividad");
        btnAgregarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActividadActionPerformed(evt);
            }
        });

        btnEliminarDiaAgenda.setText("Eliminar Dia en Agenda");
        btnEliminarDiaAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDiaAgendaActionPerformed(evt);
            }
        });

        btnVerReporteDias.setText("Ver Dias Habilitados");
        btnVerReporteDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerReporteDiasActionPerformed(evt);
            }
        });

        btnHabilitarDiaAgenda.setText("Habilitar Dia en Agenda");
        btnHabilitarDiaAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilitarDiaAgendaActionPerformed(evt);
            }
        });

        btnVerReporteActividades.setText("Ver Actividades de un Dia");
        btnVerReporteActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerReporteActividadesActionPerformed(evt);
            }
        });

        btnEliminarActividadDia.setText("Eliminar Actividad");
        btnEliminarActividadDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActividadDiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarActividadDia, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnVerReporteActividades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVerReporteDias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregarActividad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHabilitarDiaAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminarDiaAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnHabilitarDiaAgenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarActividad)
                .addGap(10, 10, 10)
                .addComponent(btnVerReporteDias)
                .addGap(8, 8, 8)
                .addComponent(btnVerReporteActividades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarDiaAgenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarActividadDia)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActividadActionPerformed
        // TODO add your handling code here:
         VentanaAgregarActividad ventanaAgregar = new VentanaAgregarActividad(this.actividades);
        ventanaAgregar.setLocationRelativeTo(null);
        ventanaAgregar.setVisible(true);
    }//GEN-LAST:event_btnAgregarActividadActionPerformed

    private void btnEliminarDiaAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDiaAgendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarDiaAgendaActionPerformed

    private void btnHabilitarDiaAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilitarDiaAgendaActionPerformed
        // TODO add your handling code here:
        VentanaHabilitarDiaAgenda ventanaHabilitar = new VentanaHabilitarDiaAgenda(this.actividades);
        ventanaHabilitar.setLocationRelativeTo(null);
        ventanaHabilitar.setVisible(true);
                                                      
    }//GEN-LAST:event_btnHabilitarDiaAgendaActionPerformed

    private void btnVerReporteDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerReporteDiasActionPerformed
        // TODO add your handling code here:
        VentanaReporteDias ventanaReporteDias = new VentanaReporteDias(actividades);
        ventanaReporteDias.setLocationRelativeTo(null);
        ventanaReporteDias.setVisible(true);
        
    }//GEN-LAST:event_btnVerReporteDiasActionPerformed

    private void btnVerReporteActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerReporteActividadesActionPerformed
        // TODO add your handling code here:
        VentanaReporteActividades ventanaReporteActividades = new VentanaReporteActividades(actividades);
        ventanaReporteActividades.setLocationRelativeTo(null);
        ventanaReporteActividades.setVisible(true);
        
    }//GEN-LAST:event_btnVerReporteActividadesActionPerformed

    private void btnEliminarActividadDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActividadDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActividadDiaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarActividad;
    private javax.swing.JButton btnEliminarActividadDia;
    private javax.swing.JButton btnEliminarDiaAgenda;
    private javax.swing.JButton btnHabilitarDiaAgenda;
    private javax.swing.JButton btnVerReporteActividades;
    private javax.swing.JButton btnVerReporteDias;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
