/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestion_de_agenda_reuniones.ventanas;

import com.mycompany.gestion_de_agenda_reuniones.Actividad;
import com.mycompany.gestion_de_agenda_reuniones.Agenda;
import com.mycompany.gestion_de_agenda_reuniones.ClaseUniversitaria;
import com.mycompany.gestion_de_agenda_reuniones.Evaluacion;
import com.mycompany.gestion_de_agenda_reuniones.Reunion;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import utilidades.GestorUI;

/**
 *
 * @author benjja
 */
public class VentanaBuscarFecha extends javax.swing.JFrame {

    /**
     * Creates new form VentanaBuscarFecha
     */
    private Agenda actividades;
    public VentanaBuscarFecha(Agenda a) {
        initComponents();
        actividades = a;
        GestorUI.cargarFechasComboBox(cbxFechas, actividades);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblActividadesFecha = new javax.swing.JTable();
        btnBuscarFecha = new javax.swing.JButton();
        cbxFechas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Buscar Fecha");

        tblActividadesFecha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Tipo Actividad", "Hora Inicio", "Hora Fin", "Titulo", "Detalle"
            }
        ));
        jScrollPane1.setViewportView(tblActividadesFecha);
        if (tblActividadesFecha.getColumnModel().getColumnCount() > 0) {
            tblActividadesFecha.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblActividadesFecha.getColumnModel().getColumn(0).setMaxWidth(120);
            tblActividadesFecha.getColumnModel().getColumn(1).setResizable(false);
            tblActividadesFecha.getColumnModel().getColumn(1).setPreferredWidth(70);
            tblActividadesFecha.getColumnModel().getColumn(2).setResizable(false);
            tblActividadesFecha.getColumnModel().getColumn(2).setPreferredWidth(70);
            tblActividadesFecha.getColumnModel().getColumn(3).setPreferredWidth(200);
            tblActividadesFecha.getColumnModel().getColumn(4).setPreferredWidth(300);
        }

        btnBuscarFecha.setText("Buscar");
        btnBuscarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cbxFechas, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarFecha)
                                .addGap(249, 249, 249))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(307, 307, 307))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarFecha)
                    .addComponent(cbxFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFechaActionPerformed
        // TODO add your handling code here:
        LocalDate fecha = GestorUI.obtenerFechaDeComboBox(cbxFechas);
        List<Actividad> listAct = actividades.getActividades(fecha);
        cargarTablaAct(listAct);
    }//GEN-LAST:event_btnBuscarFechaActionPerformed

    public void cargarTablaAct(List<Actividad> listAct){
         DefaultTableModel modelo = (DefaultTableModel) tblActividadesFecha.getModel();
        
        //  Limpiamos la tabla poniéndole 0 filas. 
        modelo.setRowCount(0);
        
        // 4. Recorremos la lista y creamos las filas
        for (Actividad act : listAct) {
            String tipoClase = act.getTipoClase();
            LocalTime horaInicio = act.getHoraInicio();
            LocalTime horaFin = act.getHoraFin();
            String titulo = act.getTitulo();
            String detalles = null;
            switch(tipoClase){
                case"REUNION":
                    Reunion auxReunion = (Reunion)act;
                    detalles = "Anfitrion: " + auxReunion.getAnfitrion();
                    modelo.addRow(new Object[]{ tipoClase.toUpperCase(),horaInicio , horaFin, titulo , detalles });
                    break;
                case"EVALUACION":
                    Evaluacion auxEvaluacion = (Evaluacion)act;
                    detalles ="Ponderación: " + auxEvaluacion.getPonderacion() + "% | Temas: " + auxEvaluacion.getTemario();
                    modelo.addRow(new Object[]{ tipoClase.toUpperCase(),horaInicio , horaFin, titulo , detalles });
                    break;
                case"CLASE":
                    ClaseUniversitaria auxClase =(ClaseUniversitaria)act;
                    detalles = "Prof: " + auxClase.getProfesor() + " | Sala: " + auxClase.getSala();
                    modelo.addRow(new Object[]{ tipoClase.toUpperCase(),horaInicio , horaFin, titulo , detalles });
                    break;
                    
            }

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarFecha;
    private javax.swing.JComboBox<String> cbxFechas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblActividadesFecha;
    // End of variables declaration//GEN-END:variables
}
