/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestion_de_agenda_reuniones.ventanas;
import com.mycompany.gestion_de_agenda_reuniones.Agenda;
import com.mycompany.gestion_de_agenda_reuniones.Actividad;
import com.mycompany.gestion_de_agenda_reuniones.ClaseUniversitaria;
import com.mycompany.gestion_de_agenda_reuniones.Evaluacion;
import com.mycompany.gestion_de_agenda_reuniones.Reunion;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import utilidades.GestorUI;

/**
 *
 * @author benjja
 */
public class VentanaEditarActividades extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEditarActividades
     */
    private Agenda actividades;
    public VentanaEditarActividades(Agenda actividades) {
        initComponents();
        this.actividades = actividades;
        ocultarCamposEspecificos();
        GestorUI.cargarFechasComboBox(cbxFechas, actividades);
        txtId.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        cbxFechas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cbxActividades = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblAnfitrion = new javax.swing.JLabel();
        txtAnfitrion = new javax.swing.JTextField();
        lblPonderacion = new javax.swing.JLabel();
        txtPonderacion = new javax.swing.JTextField();
        lblTemario = new javax.swing.JLabel();
        txtTemario = new javax.swing.JTextField();
        chbEsGrupal = new javax.swing.JCheckBox();
        lblProfesor = new javax.swing.JLabel();
        txtProfesor = new javax.swing.JTextField();
        lblSala = new javax.swing.JLabel();
        txtSala = new javax.swing.JTextField();
        lblAsignatura = new javax.swing.JLabel();
        txtAsignatura = new javax.swing.JTextField();
        txtHoraFinal = new javax.swing.JFormattedTextField();
        txtHoraInicio = new javax.swing.JFormattedTextField();
        btnGuardar = new javax.swing.JButton();

        jLabel10.setText("Anfitrion:");

        jLabel12.setText("Temario:");

        jLabel11.setText("Pondercion nota:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFechasActionPerformed(evt);
            }
        });
        getContentPane().add(cbxFechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 24, 96, -1));

        jLabel1.setText("Escoga la fecha de la actividad:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 27, -1, -1));

        cbxActividades.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxActividadesItemStateChanged(evt);
            }
        });
        cbxActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxActividadesActionPerformed(evt);
            }
        });
        getContentPane().add(cbxActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 65, 144, -1));

        jLabel2.setText("Escoga la actividad a editar: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 68, -1, -1));

        jLabel3.setText("ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 125, -1, -1));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 122, 80, -1));

        jLabel4.setText("Titulo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 160, -1, -1));
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 157, 160, -1));

        jLabel5.setText("Hora final:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 230, -1, -1));

        jLabel6.setText("Hora inicio:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 195, -1, -1));

        lblAnfitrion.setText("Anfitrion:");
        getContentPane().add(lblAnfitrion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));
        getContentPane().add(txtAnfitrion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 72, -1));

        lblPonderacion.setText("Pondercion nota:");
        getContentPane().add(lblPonderacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));
        getContentPane().add(txtPonderacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 75, -1));

        lblTemario.setText("Temario:");
        getContentPane().add(lblTemario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));
        getContentPane().add(txtTemario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 75, -1));

        chbEsGrupal.setText("Es grupal");
        chbEsGrupal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbEsGrupalActionPerformed(evt);
            }
        });
        getContentPane().add(chbEsGrupal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        lblProfesor.setText("Profesor");
        getContentPane().add(lblProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, 20));
        getContentPane().add(txtProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 72, 20));

        lblSala.setText("Sala:");
        getContentPane().add(lblSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, 20));
        getContentPane().add(txtSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 75, 20));

        lblAsignatura.setText("Asignatura:");
        getContentPane().add(lblAsignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, 20));
        getContentPane().add(txtAsignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 75, 20));

        try {
            txtHoraFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHoraFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraFinalActionPerformed(evt);
            }
        });
        getContentPane().add(txtHoraFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 60, -1));

        try {
            txtHoraInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHoraInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraInicioActionPerformed(evt);
            }
        });
        getContentPane().add(txtHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 60, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chbEsGrupalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbEsGrupalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbEsGrupalActionPerformed

    private void txtHoraFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraFinalActionPerformed

    private void txtHoraInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraInicioActionPerformed

    private void cbxFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFechasActionPerformed
        // TODO add your handling code here:
        String fechaSelec = cbxFechas.getSelectedItem().toString();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");        
        LocalDate fechaFinal = LocalDate.parse(fechaSelec, formato);
        cargarCbxActividades(fechaFinal);
        
    }//GEN-LAST:event_cbxFechasActionPerformed
    
    // Funcion 
    private void cbxActividadesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxActividadesItemStateChanged
        // TODO add your handling code here:
        if(cbxActividades.getSelectedItem()!= null){
            String textoSelecc = cbxActividades.getSelectedItem().toString();
            String[] partes = textoSelecc.split(" \\| "); 
            String tipoClase = partes[0]; 
            mostrarAtributos(tipoClase);
        }
    }//GEN-LAST:event_cbxActividadesItemStateChanged
    
    //Funcion que rellena los campos  editar de la actividad seleccionada dentro del cbxActividades
    private void cbxActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxActividadesActionPerformed
        // TODO add your handling code here:
        if(cbxActividades.getSelectedItem() != null){
          String actividadDetalles= cbxActividades.getSelectedItem().toString();
          String[] partes = actividadDetalles.split(" \\| ");
          String textoId = partes[1].replace("ID:", "").trim();
          switch(partes[0]){
              case"REUNION":
                  Reunion auxReunion = (Reunion)actividades.buscarActividad(textoId);
                  llenarCamposActividad(auxReunion);
                  txtAnfitrion.setText(auxReunion.getAnfitrion());
                  break;
              case"CLASE":
                  ClaseUniversitaria auxClase = (ClaseUniversitaria)actividades.buscarActividad(textoId);
                  llenarCamposActividad(auxClase);
                  txtProfesor.setText(auxClase.getProfesor());
                  txtSala.setText(auxClase.getSala());
                  txtAsignatura.setText(auxClase.getAsignatura());
                  break;
              case"EVALUACION":
                  Evaluacion auxEvaluacion = (Evaluacion)actividades.buscarActividad(textoId);
                  llenarCamposActividad(auxEvaluacion);
                  String ponderacion = String.valueOf(auxEvaluacion.getPonderacion());
                  txtPonderacion.setText(ponderacion);
                  txtTemario.setText(auxEvaluacion.getTemario());
                  break;
                  
          }
          

        }
        
    }//GEN-LAST:event_cbxActividadesActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        //Verificar que el usuario realmente seleccionó algo
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una actividad para editar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return; // Detiene la ejecución del botón
        }

        try {
            String idBuscado = txtId.getText();
            Actividad actividadAEditar = actividades.buscarActividad(idBuscado);

            if (actividadAEditar != null) {
                
                // 3. Actualizamos los atributos COMUNES (Los que tienen todas las actividades)
                actividadAEditar.setTitulo(txtTitulo.getText());
                actividadAEditar.setHoraInicio(LocalTime.parse(txtHoraInicio.getText()));
                actividadAEditar.setHoraFin(LocalTime.parse(txtHoraFinal.getText()));

                // 4. Actualizamos los atributos ESPECÍFICOS usando el Switch y Casteo
                switch (actividadAEditar.getTipoClase()) {
                    
                    case "REUNION":
                        Reunion r = (Reunion) actividadAEditar;
                        r.setAnfitrion(txtAnfitrion.getText());
                        break;
                        
                    case "CLASE":
                        ClaseUniversitaria c = (ClaseUniversitaria) actividadAEditar;
                        c.setProfesor(txtProfesor.getText());
                        c.setSala(txtSala.getText());
                        c.setAsignatura(txtAsignatura.getText());
                        break;
                        
                    case "EVALUACION":
                        Evaluacion e = (Evaluacion) actividadAEditar;
                        e.setTemario(txtTemario.getText());
                        e.setPNota(Double.parseDouble(txtPonderacion.getText())); 
                        e.setEsGrupal(chbEsGrupal.isSelected());
                        break;
                }

                // 5. ¡Éxito! Avisamos al usuario y cerramos la ventana de edición
                JOptionPane.showMessageDialog(this, "¡Actividad actualizada con éxito en la Agenda!", "Guardado", JOptionPane.INFORMATION_MESSAGE);
                this.dispose(); 
                
            } else {
                JOptionPane.showMessageDialog(this, "Error: No se encontró la actividad en los registros.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (java.time.format.DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Por favor, revisa el formato de las horas (HH:MM).", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa solo números válidos en la Ponderación.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_btnGuardarActionPerformed

// Funcion que rellena el cbxActividades con las actividades de la fecha seleccionada en el cbxFechas
private void cargarCbxActividades(LocalDate fechaSelec){
    List<Actividad> listAct = actividades.buscarActividades(fechaSelec);
    cbxActividades.removeAllItems();
    for( int i = 0 ; i < listAct.size() ; i ++){
        Actividad aux = listAct.get(i);
        String tipoClase = aux.getTipoClase();
        String detalles = aux.getTipoClase() + " | ID: " + aux.getId() + " | Titulo: " + aux.getTitulo();
        cbxActividades.addItem(detalles);
    
    }
}



// Funcion que oculta los campos especificos de las subclases de actividad
private void ocultarCamposEspecificos(){
        
        lblAnfitrion.setVisible(false);
        txtAnfitrion.setVisible(false);
        lblAsignatura.setVisible(false);
        lblProfesor.setVisible(false);
        lblSala.setVisible(false);
        txtAsignatura.setVisible(false);
        txtProfesor.setVisible(false);
        txtSala.setVisible(false);
        
        lblPonderacion.setVisible(false);
        lblTemario.setVisible(false);
        txtPonderacion.setVisible(false);
        txtTemario.setVisible(false);
        chbEsGrupal.setVisible(false);
             
    }

//Funcion que muestra los txt y lbl de cada tipo de actividad especifica
private void mostrarAtributos(String tipoClase){
    ocultarCamposEspecificos();
    switch(tipoClase){
        case"REUNION":
            lblAnfitrion.setVisible(true);
            txtAnfitrion.setVisible(true);
            break;
        case"CLASE":
            lblProfesor.setVisible(true);
            txtProfesor.setVisible(true);
            lblSala.setVisible(true);
            txtSala.setVisible(true);
            lblAsignatura.setVisible(true);
            txtAsignatura.setVisible(true);
            break;
        case"EVALUACION":
            lblPonderacion.setVisible(true);
            lblTemario.setVisible(true);
            chbEsGrupal.setVisible(true);
            txtPonderacion.setVisible(true);
            txtTemario.setVisible(true);
            break;


    }
}

// Funcion encargada de poner en la ventana los campos universales de cualquier tipo de actividad
private void llenarCamposActividad(Actividad act){
    txtId.setText(act.getId());
    txtTitulo.setText(act.getTitulo());
    txtHoraInicio.setText(act.getHoraInicio().toString());
    txtHoraFinal.setText(act.getHoraFin().toString());


    
}
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxActividades;
    private javax.swing.JComboBox<String> cbxFechas;
    private javax.swing.JCheckBox chbEsGrupal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblAnfitrion;
    private javax.swing.JLabel lblAsignatura;
    private javax.swing.JLabel lblPonderacion;
    private javax.swing.JLabel lblProfesor;
    private javax.swing.JLabel lblSala;
    private javax.swing.JLabel lblTemario;
    private javax.swing.JTextField txtAnfitrion;
    private javax.swing.JTextField txtAsignatura;
    private javax.swing.JFormattedTextField txtHoraFinal;
    private javax.swing.JFormattedTextField txtHoraInicio;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPonderacion;
    private javax.swing.JTextField txtProfesor;
    private javax.swing.JTextField txtSala;
    private javax.swing.JTextField txtTemario;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
