/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestion_de_agenda_reuniones.ventanas;

import com.mycompany.gestion_de_agenda_reuniones.Actividad;
import com.mycompany.gestion_de_agenda_reuniones.Agenda;
import com.mycompany.gestion_de_agenda_reuniones.ClaseUniversitaria;
import com.mycompany.gestion_de_agenda_reuniones.Evaluacion;
import com.mycompany.gestion_de_agenda_reuniones.Reunion;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tomas
 */
public class VentanaReporteActividades extends javax.swing.JFrame {

    /**
     * Creates new form VentanaReporteActividades
     */
    private Agenda actividades;
    public VentanaReporteActividades(Agenda actividades) {
        initComponents();
        this.actividades = actividades;
        cargarFechas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblPregunta = new javax.swing.JLabel();
        cbxFechas = new javax.swing.JComboBox<>();
        brnMostrarActividad = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblActividades = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPregunta.setText("¿De que fecha deseas ver las actividades?");

        brnMostrarActividad.setText("Mostrar");
        brnMostrarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnMostrarActividadActionPerformed(evt);
            }
        });

        tblActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Hora Inicio", "Hora Final", "Tipo de Actividad", "Título / Nombre", "Detalles "
            }
        ));
        jScrollPane2.setViewportView(tblActividades);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPregunta)
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(cbxFechas, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(brnMostrarActividad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblPregunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brnMostrarActividad))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarFechas(){
         cbxFechas.removeAllItems();
         DateTimeFormatter formato = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
         List<LocalDate> fechas = actividades.getDiasHabilitados();
         for( LocalDate fecha : fechas ){
         cbxFechas.addItem(fecha.format(formato));
        }
    }
    private void brnMostrarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnMostrarActividadActionPerformed
        // TODO add your handling code here:
        String fechaSelec = cbxFechas.getSelectedItem().toString();
        java.time.format.DateTimeFormatter formato = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");        LocalDate fechaFinal = LocalDate.parse(fechaSelec, formato);
        List<Actividad> listaActividades = actividades.getActividades(fechaFinal);
        DefaultTableModel modelo = (DefaultTableModel) tblActividades.getModel();
        
         for (Actividad actividad : listaActividades) {
            LocalTime horaInicio = actividad.getHoraInicio();
            LocalTime horaFin = actividad.getHoraFin();
            String tipoActividad = actividad.getTipoActividad();
            String titulo = actividad.getTitulo();
            System.out.println(tipoActividad);
            switch(tipoActividad){
                case"REUNION":
                    Reunion auxReunion = (Reunion ) actividad;
                    String anfitrion = auxReunion.getAnfitrion();
                    modelo.addRow(new Object[]{ horaInicio , horaFin,tipoActividad.toUpperCase(), titulo , anfitrion });
                    break;
                    
                case"CLASE":
                    ClaseUniversitaria auxClase = (ClaseUniversitaria) actividad;
                    String detallesClase =  "Prof: " + auxClase.getProfesor() + " | Sala: " + auxClase.getSala();
                    modelo.addRow(new Object[]{ horaInicio , horaFin,tipoActividad.toUpperCase(), titulo , detallesClase });
                    break;
                    
               case"EVALUACION":
                   Evaluacion auxEvaluacion = (Evaluacion) actividad;
                   String detallesEvaluacion ="Ponderación: " + auxEvaluacion.getPonderacion() + "% | Temas: " + auxEvaluacion.getTemario();
                   modelo.addRow(new Object[]{ horaInicio , horaFin,tipoActividad.toUpperCase(), titulo , detallesEvaluacion });
                   break;
                
                    
            }
            
        }
    }//GEN-LAST:event_brnMostrarActividadActionPerformed


    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnMostrarActividad;
    private javax.swing.JComboBox<String> cbxFechas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JTable tblActividades;
    // End of variables declaration//GEN-END:variables
}
