/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestion_de_agenda_reuniones.ventanas;

import Excepciones.CamposActividadException;
import com.mycompany.gestion_de_agenda_reuniones.Agenda;
import com.mycompany.gestion_de_agenda_reuniones.Actividad;
import com.mycompany.gestion_de_agenda_reuniones.ClaseUniversitaria;
import com.mycompany.gestion_de_agenda_reuniones.Evaluacion;
import com.mycompany.gestion_de_agenda_reuniones.Reunion;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import utilidades.GestorUI;

/**
 *
 * @author benjja
 */
public class VentanaAgregarActividad extends javax.swing.JFrame {

    private Agenda actividades;
    public VentanaAgregarActividad(Agenda actividades) {
        //Inicializamos nuestroi objeto de la clase Agenda como los componentes de la ventana
        initComponents();
        this.actividades = actividades;
        //Se utiliza el metodo statico cargarFechas() para poder llenar el cbxFechas con las fechas de la agenda
        GestorUI.cargarFechasComboBox(cbxFechas, actividades);
        this.setSize(461 , 342);
        //Ocultamos los campos espeificos al iniciar la ventana
        ocultarCamposEspecificos();
       

        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField9 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        txtId = new javax.swing.JTextField();
        cbxTipoClase = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAnfitrion = new javax.swing.JTextField();
        lblAnfitrion = new javax.swing.JLabel();
        txtProfesor = new javax.swing.JTextField();
        lblProfesor = new javax.swing.JLabel();
        txtSala = new javax.swing.JTextField();
        lblSala = new javax.swing.JLabel();
        txtAsignatura = new javax.swing.JTextField();
        lblAsignatura = new javax.swing.JLabel();
        txtPonderacionNota = new javax.swing.JTextField();
        lblPonderacionNota = new javax.swing.JLabel();
        txtTemario = new javax.swing.JTextField();
        lblTemario = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        chbxEsGrupal = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();
        txtHrInicio = new javax.swing.JFormattedTextField();
        txtHrFinal = new javax.swing.JFormattedTextField();
        cbxFechas = new javax.swing.JComboBox<>();

        jTextField9.setText("jTextField1");

        jLabel6.setText("Sala ");

        jTextField1.setText("jTextField1");

        jFormattedTextField1.setText("jFormattedTextField1");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 78, 72, -1));

        cbxTipoClase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reunion", "Evaluacion", "Clase Universitaria" }));
        cbxTipoClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoClaseActionPerformed(evt);
            }
        });
        getContentPane().add(cbxTipoClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 37, -1, -1));

        jLabel1.setText("¿Que actividad quieres agregar? :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 40, -1, -1));

        jLabel2.setText("ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 81, -1, -1));
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 113, 72, -1));

        jLabel8.setText("Titulo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 116, -1, -1));

        jLabel9.setText("Fecha:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 151, -1, -1));

        jLabel10.setText("Hora inicio ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 180, -1, -1));

        jLabel11.setText("Hora final ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 209, -1, -1));
        getContentPane().add(txtAnfitrion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 73, -1));

        lblAnfitrion.setText("Anfitrion:");
        getContentPane().add(lblAnfitrion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));
        getContentPane().add(txtProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 113, 72, -1));

        lblProfesor.setText("Profesor");
        getContentPane().add(lblProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 116, -1, -1));
        getContentPane().add(txtSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 148, 75, -1));

        lblSala.setText("Sala ");
        getContentPane().add(lblSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 151, -1, -1));
        getContentPane().add(txtAsignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 78, 95, -1));

        lblAsignatura.setText("Asingatura");
        getContentPane().add(lblAsignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 81, -1, -1));
        getContentPane().add(txtPonderacionNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 72, 20));

        lblPonderacionNota.setText("Ponderacion Nota");
        getContentPane().add(lblPonderacionNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, 20));
        getContentPane().add(txtTemario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 75, -1));

        lblTemario.setText("Temario");
        getContentPane().add(lblTemario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(724, 78, -1, -1));

        chbxEsGrupal.setText("Es un trabajo grupal");
        chbxEsGrupal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbxEsGrupalActionPerformed(evt);
            }
        });
        getContentPane().add(chbxEsGrupal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        try {
            txtHrInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtHrInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 50, -1));

        try {
            txtHrFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtHrFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 50, -1));

        cbxFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFechasActionPerformed(evt);
            }
        });
        getContentPane().add(cbxFechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

   //Funcion que permite ocultar los atributos especificos segun el tipo de clase (CLASE , EVALUACION Y REUNION).
    private void ocultarCamposEspecificos(){
        
        lblAsignatura.setVisible(false);
        lblProfesor.setVisible(false);
        lblSala.setVisible(false);
        txtAsignatura.setVisible(false);
        txtProfesor.setVisible(false);
        txtSala.setVisible(false);
        
        lblPonderacionNota.setVisible(false);
        lblTemario.setVisible(false);
        txtPonderacionNota.setVisible(false);
        txtTemario.setVisible(false);
        chbxEsGrupal.setVisible(false);
             
    }
    
    //Funcion que permite mostrar los atributos especificos segun el tipo de clase (CLASE , EVALUACION Y REUNION).
    private void cbxTipoClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoClaseActionPerformed
        // TODO add your handling code here:
        lblAnfitrion.setVisible(false);
        txtAnfitrion.setVisible(false);
        ocultarCamposEspecificos();
        String option = cbxTipoClase.getSelectedItem().toString();
        
        switch(option){
            
            case"Reunion":
                lblAnfitrion.setVisible(true);
                txtAnfitrion.setVisible(true);
                break;
                
            case"Clase Universitaria":
                lblAsignatura.setVisible(true);
                lblProfesor.setVisible(true);
                lblSala.setVisible(true);
                txtAsignatura.setVisible(true);
                txtProfesor.setVisible(true);
                txtSala.setVisible(true);
                break;
           
            case"Evaluacion":
                lblPonderacionNota.setVisible(true);
                lblTemario.setVisible(true);
                txtPonderacionNota.setVisible(true);
                txtTemario.setVisible(true);
                chbxEsGrupal.setVisible(true);
                break;
                
        }
    }//GEN-LAST:event_cbxTipoClaseActionPerformed

    private void chbxEsGrupalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbxEsGrupalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbxEsGrupalActionPerformed

    //Funcion que guarda en la agenda la nueva actividad que creo el usuario
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
         String id = txtId.getText();
         String titulo = txtTitulo.getText();
         String hrInicioStr = txtHrInicio.getText();
         String hrFinalStr= txtHrInicio.getText();
         
         //Nos aseguramos de que el usuario haya rellenado los campos principales
         if(id.isEmpty() || titulo.isEmpty() || hrInicioStr.isEmpty() || hrFinalStr.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, rellena todos los campos obligatorios antes de guardar.", "Campos Incompletos", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; 
         }
        try{
          //Obtenemos los atributos que el usuario coloco
         String fecha = cbxFechas.getSelectedItem().toString();
         DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
         LocalDate fechaFinal = LocalDate.parse(fecha, formato); 
         String tipoClase = cbxTipoClase.getSelectedItem().toString().toUpperCase();
         LocalTime hrInicio =LocalTime.parse( hrInicioStr);
         LocalTime hrFinal =LocalTime.parse( hrFinalStr);

         Actividad newAct = null;
        
         //Instancia la subclase correspondiente según el tipo de actividad seleccionado, utilizando los datos del formulario.
         switch(tipoClase){
            case "REUNION":
                  String anfitrion = txtAnfitrion.getText();
                  newAct = new Reunion(tipoClase , id , titulo  , fechaFinal , hrInicio , hrFinal , anfitrion);
                  break;
            
            case"CLASE UNIVERSITARIA":
                  String asignatura = txtAsignatura.getText();
                  String profesor = txtProfesor.getText();
                  String sala = txtSala.getText();
                  tipoClase ="CLASE";
                  newAct = new ClaseUniversitaria(tipoClase , id , titulo  , fechaFinal , hrInicio , hrFinal , asignatura , profesor , sala);
                  break;
                
            case"EVALUACION":
                  Double pondNota = Double.parseDouble(txtPonderacionNota.getText());
                  String temario = txtTemario.getText();
                  Boolean esGrupal = chbxEsGrupal.isSelected();
                
                  newAct = new Evaluacion (tipoClase , id , titulo  , fechaFinal , hrInicio , hrFinal , pondNota , temario , esGrupal);
                  break;
                
        }
        
         //Si nuestra newAct fue creada correctamente , se inserta en el mapa Actividades y se imprime un mensaje en la ventana
        if(newAct != null){
            
            actividades.agregarActividad(newAct);
            JOptionPane.showMessageDialog(this, "¡Actividad guardada con éxito!");
            this.dispose();
         }
            
        } catch(CamposActividadException e){
            //Atrapa errores relacionado a los campos que relleno el usuario 
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error de Guardado", javax.swing.JOptionPane.WARNING_MESSAGE);
        } catch (java.time.format.DateTimeParseException e) {
            // Atrapa errores si escriben mal las horas (inicio / final).
            javax.swing.JOptionPane.showMessageDialog(this, "Revisa el formato de las horas. Debe ser HH:mm (ejemplo: 08:30 o 14:00).", "Error de Formato", javax.swing.JOptionPane.ERROR_MESSAGE);
            
        } catch (NumberFormatException e) {
            // Atrapa errores si escriben texto en la ponderación de la evaluación 
            javax.swing.JOptionPane.showMessageDialog(this, "La ponderación de la nota debe ser un número válido (usa punto para decimales, ej: 25.5).", "Error Numérico", javax.swing.JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void cbxFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFechasActionPerformed
        // TODO add your handling code here:
        

        
    }//GEN-LAST:event_cbxFechasActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxFechas;
    private javax.swing.JComboBox<String> cbxTipoClase;
    private javax.swing.JCheckBox chbxEsGrupal;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblAnfitrion;
    private javax.swing.JLabel lblAsignatura;
    private javax.swing.JLabel lblPonderacionNota;
    private javax.swing.JLabel lblProfesor;
    private javax.swing.JLabel lblSala;
    private javax.swing.JLabel lblTemario;
    private javax.swing.JTextField txtAnfitrion;
    private javax.swing.JTextField txtAsignatura;
    private javax.swing.JFormattedTextField txtHrFinal;
    private javax.swing.JFormattedTextField txtHrInicio;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPonderacionNota;
    private javax.swing.JTextField txtProfesor;
    private javax.swing.JTextField txtSala;
    private javax.swing.JTextField txtTemario;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
