/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestion_de_agenda_reuniones.ventanas;
import com.mycompany.gestion_de_agenda_reuniones.Agenda;

 

/**
 *
 * @author tomas
 */
public class VentanaLauncher extends javax.swing.JFrame {

    /**
     * Creates new form VentanaLauncher
     */
    private Agenda actividades;
    public VentanaLauncher(Agenda agendaCargada) {
        initComponents();
        this.actividades = agendaCargada;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        terminalBtn = new javax.swing.JButton();
        ventanaBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Seleccione el modo de ejecución del sistema");

        terminalBtn.setText("Terminal");
        terminalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminalBtnActionPerformed(evt);
            }
        });

        ventanaBtn.setText("Interfaz Grafica");
        ventanaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventanaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(terminalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(ventanaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(terminalBtn)
                    .addComponent(ventanaBtn))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void terminalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminalBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_terminalBtnActionPerformed

    private void ventanaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventanaBtnActionPerformed
        // TODO add your handling code here:
        VentanaMenuMain ventanaMain = new VentanaMenuMain(this.actividades);
        ventanaMain.setLocationRelativeTo(null);
        ventanaMain.setVisible(true);
        
        this.dispose();
        
        
        
        
    }//GEN-LAST:event_ventanaBtnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton terminalBtn;
    private javax.swing.JButton ventanaBtn;
    // End of variables declaration//GEN-END:variables
}
